resources:
  - name: minio-registry-same
    type: s3
    source:
      endpoint: 10.3.0.2:9000
      disable_ssl: true
      regexp: same-thing/file-(.*).txt
      access_key_id: ((minio_access_key_id))
      secret_access_key: ((minio_secret_access_key))
      bucket: local-inputs

jobs:
  - name: do-the-thing
    serial: true
    plan:
    - task: make-first-input
      config:
        platform: linux
        image_resource:
          type: docker-image
          source: {repository: busybox}
        outputs:
          - name: same-thing
        run:
          path: sh
          args:
          - -c
          - |
            echo "hi alex" > same-thing/file-1.0.0.txt
    - put: minio-registry-same
      params: {file: same-thing/file-*.txt}
