jobs:
- name: start
  serial: true
  plan:
  - get: output1
    resource: minio-registry-1
  - task: make-second-input
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      outputs:
        - name: output2
      run:
        path: sh
        args:
        - -c
        - |
          echo "hows life?" > output2/file-2.0.0.txt

  - put: minio-registry-3
    params:
      file: output1/file-*.txt
  - put: minio-registry-2
    params:
      file: output2/file-*.txt

resources:
- name: minio-registry-1
  type: s3
  source:
    endpoint: 10.3.0.2:9000
    disable_ssl: true
    regexp: output1/file-(.*).txt
    access_key_id: ((minio_access_key_id))
    secret_access_key: ((minio_secret_access_key))
    bucket: local-inputs

- name: minio-registry-2
  type: s3
  source:
    endpoint: 10.3.0.2:9000
    disable_ssl: true
    regexp: output2/file-(.*).txt
    access_key_id: ((minio_access_key_id))
    secret_access_key: ((minio_secret_access_key))
    bucket: local-inputs

- name: minio-registry-3
  type: s3
  source:
    endpoint: 10.3.0.2:9000
    disable_ssl: true
    regexp: output3/file-(.*).txt
    access_key_id: ((minio_access_key_id))
    secret_access_key: ((minio_secret_access_key))
    bucket: local-inputs
