jobs:
- name: start
  serial: true
  plan:
  - task: make-first-input
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      outputs:
        - name: output1
      run:
        path: sh
        args:
        - -c
        - |
          echo "hi alex" > output1/file-1.0.0.txt
  - task: make-second-input
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      outputs:
        - name: output2
      run:
        path: sh
        args:
        - -c
        - |
          echo "hows life?" > output2/file-2.0.0.txt
  - task: use-the-inputs
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: busybox}
      inputs:
      - name: output1
      - name: output2
      run:
        path: sh
        args:
        - -c
        - |
          cat output1/file*
          cat output2/file*
