jobs:
- name: hangar
  public: true
  plan:
  - get: hangar
    trigger: true
  - task: build
    file: hangar/build.yml

resources:
- name: hangar
  type: git
  source:
    uri: https://github.com/concourse/hangar.git
    branch: master
