---
resources:
- name: timer
  type: time
  source:
    interval: 10m

- name: large-file
  type: bosh-io-stemcell
  source:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent

jobs:
- name: vsphere-test
  plan:
  - get: timer
    trigger: true
  - get: large-file
    timeout: 5m
    tags: [pizza]
  - task: hash
    config:
      platform: linux
      inputs:
        - name: large-file
      run:
        path: /bin/sh
        args:
          - -e
          - -c
          - md5sum large-file/*.tgz


