---
resources:
- name: t1
  type: time
  source: {interval: 1m}

jobs:
- name: t1-no-trigger
  plan:
  - get: t1

- name: t1-trigger
  plan:
  - get: t1
    trigger: true

- name: t1-constrained-no-trigger
  plan:
  - get: t1
    passed: [t1-trigger]

- name: t1-constrained-trigger
  plan:
  - get: t1
    passed: [t1-trigger]
    trigger: true

- name: t1-constrained-fan-in-no-trigger
  plan:
  - get: t1
    passed: [t1-trigger, t1-no-trigger]

- name: t1-constrained-fan-in-trigger
  plan:
  - get: t1
    passed: [t1-trigger, t1-no-trigger]
    trigger: true

- name: t1-constrained-fan-in-skipping-triggerless-no-trigger
  plan:
  - get: t1
    passed: [t1-no-trigger, t1-constrained-no-trigger]

- name: t1-constrained-fan-in-skipping-triggerless-trigger
  plan:
  - get: t1
    passed: [t1-no-trigger, t1-constrained-no-trigger]
    trigger: true

- name: t1-constrained-fan-in-skipping-triggerful-no-trigger
  plan:
  - get: t1
    passed: [t1-trigger, t1-constrained-trigger]

- name: t1-constrained-fan-in-skipping-triggerful-trigger
  plan:
  - get: t1
    passed: [t1-trigger, t1-constrained-trigger]
    trigger: true

- name: t1-constrained-fan-in-skipping-mixed-1-no-trigger
  plan:
  - get: t1
    passed: [t1-trigger, t1-constrained-no-trigger]

- name: t1-constrained-fan-in-skipping-mixed-2-no-trigger
  plan:
  - get: t1
    passed: [t1-no-trigger, t1-constrained-trigger]

- name: t1-constrained-fan-in-skipping-mixed-1-trigger
  plan:
  - get: t1
    passed: [t1-trigger, t1-constrained-no-trigger]
    trigger: true

- name: t1-constrained-fan-in-skipping-mixed-2-trigger
  plan:
  - get: t1
    passed: [t1-no-trigger, t1-constrained-trigger]
    trigger: true
