jobs:
- name: buildroot-tarmaker
  serial: true
  public: true
  plan:
  - aggregate:
    - get: buildroot-tarmaker
      trigger: true
    - get: ubuntu-16.04
      params: {save: true}
      trigger: true
  - put: buildroot-tarmaker-image
    params:
      build: buildroot-tarmaker
      dockerfile: buildroot-tarmaker/Dockerfile.tarmaker
      load_base: ubuntu-16.04

- name: buildroot-base
  serial: true
  public: true
  plan:
  - aggregate:
    - get: buildroot-images
      resource: buildroot-base
      trigger: true
    - get: buildroot
      trigger: true
    - get: buildroot-tarmaker-image
      params: {save: true}
      passed: [buildroot-tarmaker]
      trigger: true
  - task: build-image
    privileged: true
    file: buildroot-images/ci/build.yml
    params:
      FLAVOR: base
  - put: buildroot-base-image
    params: {build: image-root}

- name: buildroot-git
  serial: true
  public: true
  plan:
  - aggregate:
    - get: buildroot-images
      resource: buildroot-git
      trigger: true
    - get: buildroot
      trigger: true
    - get: buildroot-tarmaker-image
      params: {save: true}
      passed: [buildroot-tarmaker]
      trigger: true
  - task: build-image
    privileged: true
    file: buildroot-images/ci/build.yml
    params:
      FLAVOR: git
  - put: buildroot-git-image
    params: {build: image-root}

- name: buildroot-curl
  serial: true
  public: true
  plan:
  - aggregate:
    - get: buildroot-images
      resource: buildroot-curl
      trigger: true
    - get: buildroot
      trigger: true
    - get: buildroot-tarmaker-image
      params: {save: true}
      passed: [buildroot-tarmaker]
      trigger: true
  - task: build-image
    privileged: true
    file: buildroot-images/ci/build.yml
    params:
      FLAVOR: curl
  - put: buildroot-curl-image
    params: {build: image-root}

- name: buildroot-ruby
  serial: true
  public: true
  plan:
  - aggregate:
    - get: buildroot-images
      resource: buildroot-ruby
      trigger: true
    - get: buildroot
      trigger: true
    - get: buildroot-tarmaker-image
      params: {save: true}
      passed: [buildroot-tarmaker]
      trigger: true
  - task: build-image
    privileged: true
    file: buildroot-images/ci/build.yml
    params:
      FLAVOR: ruby
  - put: buildroot-ruby-image
    params: {build: image-root}

- name: datadog-event-resource
  serial: true
  public: true
  plan:
  - aggregate:
    - get: buildroot-base-image
      params: {save: true}
      passed: [buildroot-base]
      trigger: true
    - get: datadog-event-resource
      trigger: true
  - task: unit-and-build
    file: datadog-event-resource/build.yml
  - put: datadog-event-resource-image
    params:
      load_base: buildroot-base-image
      build: built-resource

- name: bosh-deployment-resource
  serial: true
  public: true
  plan:
  - aggregate:
    - get: buildroot-ruby-image
      params: {save: true}
      passed: [buildroot-ruby]
      trigger: true
    - get: bosh-deployment-resource
      trigger: true
  - task: unit
    file: bosh-deployment-resource/build.yml
  - put: bosh-deployment-resource-image
    params:
      load_base: buildroot-ruby-image
      build: bosh-deployment-resource

- name: bump-bosh-deployment-resource
  serial: true
  public: true
  plan:
  - get: bosh-deployment-resource-image
    passed: [bosh-deployment-resource]
    params: {rootfs: true}
    trigger: true
  - get: bosh-deployment-resource
    passed: [bosh-deployment-resource]
  - get: concourse
  - task: bump-package
    input_mapping:
      resource-image: bosh-deployment-resource-image
      resource-repo: bosh-deployment-resource
    file: concourse/ci/bump-resource-package.yml
    params:
      RESOURCE_NAME: bosh-deployment-resource
      BOSH_PRIVATE_CONFIG: ((concourse_release_private_config))
  - put: concourse
    params: {repository: bumped-concourse, rebase: true}

- name: semver-resource
  serial: true
  public: false # easy to leak bucket params
  plan:
  - aggregate:
    - get: buildroot-git-image
      params: {save: true}
      passed: [buildroot-git]
      trigger: true
    - get: semver-resource
      trigger: true
  - task: unit
    file: semver-resource/build.yml
    params:
      SEMVER_TESTING_ACCESS_KEY_ID: ((semver_resource_bucket.access_key))
      SEMVER_TESTING_SECRET_ACCESS_KEY: ((semver_resource_bucket.secret_key))
      SEMVER_TESTING_BUCKET: ((semver_resource.bucket))
      SEMVER_TESTING_REGION: ((semver_resource.region))
  - put: semver-resource-image
    params:
      load_base: buildroot-git-image
      build: built-resource

- name: bump-semver-resource
  serial: true
  public: false # easy to leak bucket params
  plan:
  - get: semver-resource-image
    passed: [semver-resource]
    params: {rootfs: true}
    trigger: true
  - get: semver-resource
    passed: [semver-resource]
  - get: concourse
  - task: bump-package
    input_mapping:
      resource-image: semver-resource-image
      resource-repo: semver-resource
    file: concourse/ci/bump-resource-package.yml
    params:
      RESOURCE_NAME: semver-resource
      BOSH_PRIVATE_CONFIG: ((concourse_release_private_config))
  - put: concourse
    params: {repository: bumped-concourse, rebase: true}

- name: tracker-resource
  serial: true
  public: true
  plan:
  - aggregate:
    - get: buildroot-git-image
      params: {save: true}
      passed: [buildroot-git]
      trigger: true
    - get: tracker-resource
      trigger: true
  - task: unit
    file: tracker-resource/build.yml
    params:
      TRACKER_TOKEN: ((tracker_resource.token))
  - put: tracker-resource-image
    params:
      load_base: buildroot-git-image
      build: built-resource

- name: bump-tracker-resource
  serial: true
  public: true
  plan:
  - get: tracker-resource-image
    passed: [tracker-resource]
    params: {rootfs: true}
    trigger: true
  - get: tracker-resource
    passed: [tracker-resource]
  - get: concourse
  - task: bump-package
    input_mapping:
      resource-image: tracker-resource-image
      resource-repo: tracker-resource
    file: concourse/ci/bump-resource-package.yml
    params:
      RESOURCE_NAME: tracker-resource
      BOSH_PRIVATE_CONFIG: ((concourse_release_private_config))
  - put: concourse
    params: {repository: bumped-concourse, rebase: true}

resources:
- name: datadog-event-resource
  type: git
  source:
    uri: https://github.com/concourse/datadog-event-resource.git
    branch: master

- name: tracker-resource
  type: git
  source:
    uri: https://github.com/concourse/tracker-resource.git
    branch: master

- name: semver-resource
  type: git
  source:
    uri: https://github.com/concourse/semver-resource.git
    branch: master

- name: bosh-deployment-resource
  type: git
  source:
    uri: https://github.com/concourse/bosh-deployment-resource.git
    branch: master

- name: bosh-deployment-resource-image
  type: docker-image
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: concourse/bosh-deployment-resource

- name: datadog-event-resource-image
  type: docker-image
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: concourse/datadog-event-resource

- name: tracker-resource-image
  type: docker-image
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: concourse/tracker-resource

- name: semver-resource-image
  type: docker-image
  source:
    username: ((docker.username))
    password: ((docker.password))
    repository: concourse/semver-resource

- name: concourse
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    branch: master
    private_key: ((concourse_repo_private_key))

- name: buildroot
  type: git
  source:
    uri: git://git.buildroot.net/buildroot
    tag_filter: '[0-9][0-9][0-9][0-9].[0-9][0-9]'

- name: buildroot-tarmaker
  type: git
  source:
    uri: https://github.com/concourse/buildroot-images.git
    branch: master
    paths: [Dockerfile.tarmaker]

- name: buildroot-tarmaker-image
  type: docker-image
  source:
    repository: concourse/buildroot-tarmaker
    username: ((docker.username))
    password: ((docker.password))

- name: buildroot-base
  type: git
  source:
    uri: https://github.com/concourse/buildroot-images.git
    branch: master
    paths: [base, ci]

- name: buildroot-base-image
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: base
    username: ((docker.username))
    password: ((docker.password))

- name: buildroot-git
  type: git
  source:
    uri: https://github.com/concourse/buildroot-images.git
    branch: master
    paths: [git, ci]

- name: buildroot-git-image
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: git
    username: ((docker.username))
    password: ((docker.password))

- name: buildroot-curl
  type: git
  source:
    uri: https://github.com/concourse/buildroot-images.git
    branch: master
    paths: [curl, ci]

- name: buildroot-curl-image
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: curl
    username: ((docker.username))
    password: ((docker.password))

- name: buildroot-ruby
  type: git
  source:
    uri: https://github.com/concourse/buildroot-images.git
    branch: master
    paths: [ruby, ci]

- name: buildroot-ruby-image
  type: docker-image
  source:
    repository: concourse/buildroot
    tag: ruby
    username: ((docker.username))
    password: ((docker.password))

- name: ubuntu-16.04
  type: docker-image
  source:
    repository: ubuntu
    tag: "16.04"
