jobs:
  - name: bosh-deploy-final-release
    plan:
    - aggregate:
      - get: github-release
      - get: bosh-stemcell
        resource: gcp-stemcell
      - get: deployments
    - put: wings-deployment
      params:
        cleanup: true
        manifest: deployments/prod/deployments/wings.yml
        stemcells: [bosh-stemcell/*.tgz]
        releases:
          - github-release/concourse-*.tgz
          - github-release/garden-runc-*.tgz

  - name: bosh-deploy-nightly
    plan:
    - aggregate:
      - get: nightly-release
        trigger: true
      - get: garden-runc
      - get: bosh-stemcell
        resource: gcp-stemcell
      - get: deployments
    - put: notify-concourse-wings
      params:
        text: "Nightly deployment is starting"
    - put: wings-deployment
      params:
        cleanup: true
        manifest: deployments/prod/deployments/wings.yml
        releases:
        - garden-runc/*.tgz
        - nightly-release/concourse-*.tgz
        stemcells:
        - bosh-stemcell/*.tgz
    - put: notify-concourse-wings
      params:
        text: "Nightly deployment finished"


resources:
- name: wings-deployment
  type: bosh-deployment
  source:
    target: ((bosh_target))
    deployment: concourse-wings
    client: ((bosh_client.id))
    client_secret: ((bosh_client.secret))

- name: github-release
  type: github-release
  source:
    access_token: ((concourse_github_release.access_token))
    repository: concourse
    user: concourse

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: deployments
  type: git
  source:
    uri: git@github.com:concourse/deployments.git
    branch: master
    private_key: ((deployments_repo_private_key))

- name: nightly-release
  type: s3
  source:
    bucket: concourse-nightly-releases
    regexp: concourse-(.*).tgz
    region_name: us-west-2

- name: garden-runc
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

- name: notify-concourse-wings
  type: slack-notification
  source:
    url: https://hooks.slack.com/services/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

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
