jobs:
  - name: bosh-deploy-final-release
    serial_groups: [deploy]
    plan:
    - aggregate:
      - get: github-release
      - get: bosh-stemcell
        resource: gcp-stemcell
      - get: deployments
    - put: wings-deployment
      params:
        cleanup: true
        manifest: deployments/prod/deployments/wings.yml
        stemcells: [bosh-stemcell/*.tgz]
        releases:
          - github-release/concourse-*.tgz
          - github-release/garden-runc-*.tgz

  - name: prepare-nightly
    serial_groups: [deploy]
    plan:
    - aggregate:
      - get: nightly-release
      - get: garden-runc
      - get: bosh-stemcell
        resource: gcp-stemcell
      - get: deployments
      - get: from-commit
        resource: last-deployment
      - get: to-commit
        resource: latest-nightly
      - get: concourse
    - task: compose-message
      file: concourse/ci/issues-for-commit-range.yml
      params:
        FROM_COMMIT_FILE: last-deployment/ref
        TO_COMMIT_FILE: latest-nightly/ref
        HEADING: |
          *Preparing RC for deployment to Wings*. \n
          Here is a list of issues closed in this RC:
    - put: notify-concourse-wings
      params:
        text_file: message/text

  - name: bosh-deploy-nightly
    serial_groups: [deploy]
    plan:
    - aggregate:
      - get: nightly-release
        passed: [prepare-nightly]
      - get: garden-runc
        passed: [prepare-nightly]
      - get: bosh-stemcell
        resource: gcp-stemcell
        passed: [prepare-nightly]
      - get: deployments
        passed: [prepare-nightly]
      - get: latest-nightly
        passed: [prepare-nightly]
    - put: wings-deployment
      params:
        cleanup: true
        manifest: deployments/prod/deployments/wings.yml
        releases:
        - garden-runc/*.tgz
        - nightly-release/concourse-*.tgz
        stemcells:
        - bosh-stemcell/*.tgz
    - put: last-deployment
      params:
        file: latest-nightly/ref
    - put: notify-concourse-wings
      params:
        text: "Nightly deployment finished"


resources:
- name: wings-deployment
  type: bosh-deployment
  source:
    target: ((bosh_target))
    deployment: concourse-wings
    client: ((bosh_client.id))
    client_secret: ((bosh_client.secret))

- name: github-release
  type: github-release
  source:
    access_token: ((concourse_github_release.access_token))
    repository: concourse
    user: concourse

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: deployments
  type: git
  source:
    uri: git@github.com:concourse/deployments.git
    branch: master
    private_key: ((deployments_repo_private_key))

- name: nightly-release
  type: s3
  source:
    bucket: concourse-nightly-releases
    regexp: concourse-(.*).tgz
    region_name: us-west-2

- name: garden-runc
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

- name: notify-concourse-wings
  type: slack-notification
  source:
    url: ((wings_webhook_url))


- name: latest-nightly
  type: s3
  source:
    bucket: concourse-nightly-releases
    versioned_file: latest-nightly/ref
    region_name: us-west-2
    access_key_id: ((concourse_release_bucket.access_key))
    secret_access_key: ((concourse_release_bucket.secret_key))

- name: last-deployment
  type: s3
  source:
    bucket: concourse-nightly-releases
    versioned_file: last-deployment/ref
    region_name: us-west-2
    access_key_id: ((concourse_release_bucket.access_key))
    secret_access_key: ((concourse_release_bucket.secret_key))

- name: concourse
  type: git
  source:
    uri: git@github.com:concourse/concourse.git
    branch: master
    private_key: ((concourse_repo_private_key))

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource

- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest
