jobs:
  - name: bosh-deploy-final-release
    plan:
    - aggregate:
      - get: github-release
      - get: bosh-stemcell
        resource: gcp-stemcell
      - get: deployments
    - put: wings-deployment
      params:
        cleanup: true
        manifest: deployments/prod/deployments/wings.yml
        stemcells: [bosh-stemcell/*.tgz]
        releases:
          - github-release/concourse-*.tgz
          - github-release/garden-runc-*.tgz

  - name: dry-run-bosh-deploy-rc
    plan:
    - aggregate:
      - get: bosh-rc
      - get: garden-runc
      - get: bosh-stemcell
        resource: gcp-stemcell
      - get: deployments
    - put: wings-deployment
      params:
        cleanup: true
        manifest: deployments/prod/deployments/wings.yml
        stemcells: [bosh-stemcell/*.tgz]
        dry_run: true
        releases:
          - garden-runc/*.tgz
          - bosh-rc/concourse-*.tgz

  - name: bosh-deploy-rc
    plan:
    - aggregate:
      - get: bosh-rc
        passed: [dry-run-bosh-deploy-rc]
      - get: garden-runc
        passed: [dry-run-bosh-deploy-rc]
      - get: bosh-stemcell
        passed: [dry-run-bosh-deploy-rc]
        resource: gcp-stemcell
      - get: deployments
        passed: [dry-run-bosh-deploy-rc]
    - put: wings-deployment
      params:
        cleanup: true
        manifest: deployments/prod/deployments/wings.yml
        stemcells: [bosh-stemcell/*.tgz]
        releases:
          - garden-runc/*.tgz
          - bosh-rc/concourse-*.tgz

resources:
- name: wings-deployment
  type: bosh-deployment
  source:
    target: ((bosh_target))
    deployment: concourse-wings
    client: ((bosh_client.id))
    client_secret: ((bosh_client.secret))

- name: github-release
  type: github-release
  source:
    access_token: ((concourse_github_release.access_token))
    repository: concourse
    user: concourse

- name: gcp-stemcell
  type: bosh-io-stemcell
  source:
    name: bosh-google-kvm-ubuntu-trusty-go_agent

- name: deployments
  type: git
  source:
    uri: git@github.com:concourse/deployments.git
    branch: master
    private_key: ((deployments_repo_private_key))

- name: bosh-rc
  type: s3
  source:
    bucket: concourse-release-candidates
    regexp: concourse-(.*).tgz

- name: garden-runc
  type: bosh-io-release
  source:
    repository: cloudfoundry/garden-runc-release

resource_types:
- name: bosh-deployment
  type: docker-image
  source:
    repository: cloudfoundry/bosh-deployment-resource
