---
platform: linux

image: /var/vcap/packages/git_resource

params:
  ENDPOINT:
  USERNAME:
  PASSWORD:
  BUILD:

run:
  path: sh
  args:
  - -c
  - |
    set -e -x
    curl "$ENDPOINT/api/v1/cli?arch=amd64&platform=linux" -o ./fly
    chmod +x ./fly
    { echo "$USERNAME"; echo "$PASSWORD"; } | ./fly -t endpoint login -c $ENDPOINT -k
    ./fly -t endpoint watch -b "$BUILD"
