---
platform: linux

image_resource:
  type: docker-image
  source: {repository: concourse/buildroot, tag: git}

params:
  AIRBUS_USERNAME:
  AIRBUS_PASSWORD:

inputs:
- name: git-pipelines

run:
  path: git-pipelines/airbus.concourse.ci/clara/tasks/scripts/hijack-task
