---
jobs:
- name: darwin
  plan:
  - task: hello
    config:
      platform: darwin
      run:
        path: echo
        args: ['Hello, world!']
- name: linux
  plan:
  - task: hello
    config:
      platform: linux
      run:
        path: echo
        args: ['Hello, world!']
- name: windows
  plan:
  - task: hello
    config:
      platform: windows
      run:
        path: echo
        args: ['Hello, world!']
